version = 0.1
[development.deploy.parameters]
stack_name = "lamabook-development-stack"
s3_bucket = <bucket_name>
s3_prefix = "lamabook-development"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"development\""

[production.deploy.parameters]
stack_name = "lamabook-production-stack"
s3_bucket = <bucket_name>
s3_prefix = "lamabook-production"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"production\""
